EOS: return LexEof( lexer );
LINE: LexLine( lexer ); goto LEX;
NOT: return LexNot( lexer );
STR: return LexStr( lexer );
COMMENT: LexComment( lexer ); goto LEX;
MOD: return LexMod( lexer );
BAND: return LexBand( lexer );
LP: return LexLp( lexer );
RP: return LexRp( lexer );
MUL: return LexMul( lexer );
ADD: return LexAdd( lexer );
COMMA: return LexComma( lexer );
SUB: return LexSub( lexer );
DOT: return LexDot( lexer );
DIV: return LexDiv( lexer );
NUM: return LexNum( lexer, &&NUM, ascii );
COLON: return LexColon( lexer );
SEMI: return LexSemi( lexer );
LT: return LexLt( lexer );
EQ: return LexEq( lexer );
GT: return LexGt( lexer );
RET: return LexReturn( lexer );
ID: return LexId( lexer, &&ID, &&NUM, ascii );
LS: return LexLs( lexer );
RS: return LexRs( lexer );
BXOR: return LexBxor( lexer );
BNOT: return LexBnot( lexer );
LC: return LexLc( lexer );
BOR: return LexBor( lexer );
RC: return LexRc( lexer );